###############################################################################
#   @author         :   Jeffrey Stone 
#   @date           :   06/10/2020
#   @package        :   Database
#   @description    :   Recorder and Logger Configurations 
###############################################################################

recorder:
  db_url: !secret database
  purge_keep_days: 35
  exclude:
    domains:
      - automation
      - weblink
      - updater
      - script
    entities:
      - sun.sun # Don't record sun data
      - sensor.last_boot # Comes from 'systemmonitor' sensor platform
      - sensor.date
      - sensor.icloud3_event_log
      - sensor.time
      - sensor.today_is
      - sensor.time_utc
      - sensor.time_date
      - sensor.time_online
      - sensor.moon
      - sensor.month_is
      - sensor.low_battery
      
logbook:
  include:
    domains:
      - media_player
      - automation
      - script
      - scene
      - light
      - switch
      - device_tracker
      - input_boolean
      - person
      - event
      - timer
      - service
      - binary_sensor
      - sensor

# Lets try to make the logs less chatty and more fine tuned.       
logger:
  default: error

history:
  include:
    domains:
      - binary_sensor
      - sensor
      - switch
      - media_player
      - light
      - scene
      - automation
