# - platform: alpha_vantage
#   api_key: !secret alpha_vantage
#   symbols:
#     #- symbol: SIRI
#     #  name: Sirius
#     #- symbol: BAC
#     #  name: BoA
#     #- symbol: INTC
#     #  name: Intel
    # - symbol: DIS
    #   name: Disney
#     #- symbol: BKS 
#     #  name: Barnes & Noble
# - platform: mqtt
#   name: "Disney"
#   state_topic: "stock/DIS/price"
# - platform: mqtt
#   name: "BoA"
#   state_topic: "stock/BAC/price"
# - platform: mqtt
#   name: "Intel"
#   state_topic: "stock/INTC/price"
# - platform: mqtt
#   name: "Sirius"
#   state_topic: "stock/SIRI/price"
# - platform: mqtt
#   name: "Barnes and Nobel"
#   state_topic: "stock/BKS/price"
#sensor:
- platform: statistics
  name: xlm_price_stats
  entity_id: sensor.xlm_exchange_rate
  state_characteristic: change
  sampling_size: 2


