- platform: template
  sensors:
    jeff_speed:
      friendly_name: "Jeff Speed"
      unit_of_measurement: 'mph'
      value_template: "{{ state_attr('device_tracker.jeffrey_stone', 'speed') | round(default=0) | float / 1.609 | round }}"
    kat_speed:
      friendly_name: "Kat Speed"
      unit_of_measurement: 'mph'
      value_template: "{{ state_attr('device_tracker.life360_kat_stone', 'speed') | round(default=0) | int }}"

  