

#################################################################################
### Groups ###

Family:
  - person.jeffrey
  - person.katherine
  - person.uncle_matt
  - person.papa

People:
  - person.jeffrey
  - person.katherine
  - sensor.skylar_location
  - person.uncle_matt
  - person.papa

test:
  - group.jeffrey
  - group.kat

jeffrey:
  - device_tracker.jeffrey_s_iphone_11_app
  - device_tracker.jeffreys_iphone_11
  - device_tracker.life360_jeffrey_stone

kat:
  - device_tracker.iphone_app
  - device_tracker.life360_kat_stone

arriving:
  name: Arriving
  entities: []

kitchen_occupancy:
  name: "Kitchen occupancy"
  entities: []

living_room_occupancy:
  entities: []

theater_occupancy:
  entities: []

studio_occupancy:
  entities: []

deck_occupancy:
  entities: []

skylars_bedroom_occupancy:
  entities: []

#- binary_sensor.skylars_bedroom_motion
occupancy:
  - binary_sensor.living_room_motion
  - binary_sensor.kitchen_motion
  - binary_sensor.pantry_motion
  - binary_sensor.bar_motion
  - binary_sensor.master_bedroom_motion
  - binary_sensor.slacker_labs_motion
  - binary_sensor.cricut_desk_motion
  - binary_sensor.dungeon_motion
  - binary_sensor.pot_studio_motion
  - binary_sensor.back_door_motion
  - binary_sensor.theater_motion
  - binary_sensor.exercise_motion
  - binary_sensor.stairs_motion_top
  - binary_sensor.stairs_motion_bottom
  - binary_sensor.roomsense_pir_f412fae8c830

rooms:
  - bomary_sensor.theater_occupied
  - binary_sensor.kitchen_occupied
  - binary_sensor.living_room_occupied
  - binary_sensor.master_bedroom_occupied
  - binary_sensor.skylars_bedroom_occupied
  - binary_sensor.studio_occupied
  - binary_sensor.pot_studio_occupied
  - binary_sensor.exercise_room_occupied
  
occupancy_night:
  - binary_sensor.living_room_motion
  - binary_sensor.kitchen_motion
  - binary_sensor.pantry_motion
  - binary_sensor.bar_motion
  - binary_sensor.master_bedroom_motion
  - binary_sensor.slacker_labs_motion
  - binary_sensor.cricut_desk_motion
  - binary_sensor.dungeon_motion
  - binary_sensor.pot_studio_motion
  - binary_sensor.roomsense_pir_f412fae8c830

stairs_occupancy:
  - binary_sensor.stairs_motion_bottom
  - binary_sensor.stairs_motion_top_occupancy

room_presence:
  - sensor.jeff_room
  - sensor.kat_room
  - sensor.skylar_room
  
jeff_room:
  - sensor.jeffs_iphone_11
  - sensor.jeffs_watch

kat_room:
  - sensor.kats_iphone_11
  - sensor.kats_watch

audio_devices:
  - media_player.kitchen_display
  - media_player.upstairs_speaker
  - media_player.master_bedroom_speaker
  - media_player.croft_speaker
  - media_player.studio_speaker
  - media_player.skylars_bedroom_speaker
  - media_player.theater

all_echos:
  - media_player.living_room_echo
  - media_player.skylars_room
  - media_player.slacker_labs_echo
  - media_player.theater_echo
  - media_player.basement_echo
  - media_player.master_bedroom_echo

Outside Lights:
  - light.front_porch_lights
  - switch.deck_lights
  - switch.driveway_light
  
External Doors:
  - binary_sensor.kitchen_door
  - binary_sensor.front_door
  - binary_sensor.back_door
  - binary_sensor.basement_door
  - binary_sensor.garage_door

Garage Doors:
  - binary_sensor.side_door
  - binary_sensor.garage_door

Internal Doors:
  - binary_sensor.attic_door

rgb lr:
  - light.front_door_lamp
  - light.living_room_lamp
  - light.living_room_tower_lamp

livingroom lighting:
  - light.front_door_lamp
  - light.living_room_lamp
  - light.living_room_tower_lamp
  - switch.fireplace_lights

livingroom lights:
  - light.front_door_lamp
  - light.living_room_lamp
  - switch.fireplace_lights
  
livingroom tower:
  - light.living_room_tower_lamp

livingroom lamps:
  - light.living_room_lamp
  - light.front_door_lamp

incense:
  - switch.forest_incense_incense
  - switch.artemis
  - switch.incense

onlyfans:
  - switch.croft_fan
  - switch.livingroom_fan

Skylars Bedroom:
  - light.skylars_dresser_lamp
  - switch.rainbow_lamp # rainbow light
  - light.wled_skylarsroom
  - switch.skylars_desk

Master Bedroom:
  - light.jeffs_lamp
  - light.kats_lamp
  - light.master_bedroom_tower_lamp

driveway_motion:
  - binary_sensor.aarlo_motion_driveway_camera
  - binary_sensor.aarlo_motion_car_port

critical_batteries:
  - sensor.aarlo_battery_level_driveway_camera
  - sensor.aarlo_battery_level_car_port
  - sensor.ring_battery


kitchen:
  - light.kitchen_cabinets
  - switch.kitchen_light_strip

livingroom:
  - light.front_door_lamp
  - light.living_room_lamp
  - light.living_room_tower_lamp
  - switch.fireplace_lights
  - switch.rail_lights

vacation lights:
  - light.front_door_lamp
  - light.living_room_lamp
  - light.living_room_tower_lamp
  - light.skylars_dresser_lamp
  - light.kitchen_sink
  - light.master_bedroom_tower_lamp
  - light.jeff_lamp
  - switch.fireplace_lights

theater lights:
  - light.theater_lights


weather_alerts:
  - sensor.fayette_alert_1
  - sensor.fayette_alert_2
  - sensor.fayette_alert_3
  - sensor.fayette_alert_4
  - sensor.fayette_alert_5