activate_work_time:
  alias: Activate Work time
  sequence:
  - service: input_select.select_option
    data:
      option: Work
    target:
      entity_id: input_select.studio_mode
  mode: single
activate_film_time:
  alias: Activate Film Time
  sequence:
  - service: input_select.select_option
    data:
      option: Film
    target:
      entity_id: input_select.studio_mode
  mode: single
activate_cone_of_silence:
  alias: Activate Cone of Silence
  sequence:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.slacker_labs_on_air
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id: input_boolean.work_background
  mode: single
deactivate_cone_of_silence:
  alias: Deactivate Cone of silence
  sequence:
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.slacker_labs_on_air
  mode: single
mud_time:
  alias: Mud Time
  sequence:
  - service: input_boolean.turn_on
    data: {}
    target:
      entity_id: input_boolean.chimichanga_mode
  mode: single
  icon: mdi:deathly-hallows
art_done:
  alias: Art Done
  sequence:
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id: input_boolean.chimichanga_mode
  mode: single
  icon: mdi:artstation
madame_leotta:
  alias: Madame Leotta
  sequence:
  - service: switch.toggle
    data: {}
    target:
      entity_id: switch.madame_leotta
  mode: single
haunted_clock:
  alias: Haunted Clock
  sequence:
  - service: switch.toggle
    data: {}
    target:
      entity_id: switch.haunted_clock
  mode: single
skeleton_seesaw:
  alias: skeleton_seesaw
  sequence:
  - service: switch.toggle
    data: {}
    target:
      entity_id: switch.skeletons
  mode: single
